

set(Monocle_Core_SOURCES
	./Config/JSONConfig.cpp
./Config/JSONConfig.h
./Containers/Array/Array.h
./Containers/AssetRegistry/ObjectRegistry.h
./Containers/AssetRegistry/ObjectRegistry.inl
./Containers/FreeList/detail/FreeListObject.h
./Containers/FreeList/Freelist.h
./Containers/FreeList/Freelist.hpp
./Containers/FreeList/PolymorphicFreelist.h
./Containers/FreeList/PolymorphicFreelist.hpp
./Containers/HashMap/HashMap.h
./Containers/IntrusiveListNode.h
./Containers/ObjectPool/ObjectPool.h
./Containers/Private/IntrusiveListNode.internal.hpp
./Containers/SparseArray/SparseArray.h
./Containers/Vector/Vector.h
./Debugger/moeDebugger.h
./Delegates/Delegate.h
./Delegates/Event.h
./Delegates/EventDelegateID.h
./Exception/RuntimeException.h
./HashString/HashString.h
./Log/ILogger.h
./Log/LogUtils.h
./Log/moeLog.h
./Log/moeLogger.h
./Log/moeLogMacros.h
./Log/Policies/CaptureWritePolicy.h
./Log/Policies/DebuggerFormatPolicy.h
./Log/Policies/FileWritePolicy.h
./Log/Policies/IdeWritePolicy.h
./Log/Policies/NoFilterPolicy.h
./Log/Policies/NoFormatPolicy.h
./Log/Policies/NoWritePolicy.h
./Log/Policies/OutStreamWritePolicy.h
./Log/Policies/SeverityFilterPolicy.h
./Log/Private/ILogger.cpp
./Log/Private/ILogger.internal.hpp
./Log/Private/LogUtils.cpp
./Log/Private/moeLogger.internal.hpp
./Log/Private/Policies/CaptureWritePolicy.cpp
./Log/Private/Policies/DebuggerFormatPolicy.cpp
./Log/Private/Policies/FileWritePolicy.cpp
./Log/Private/Policies/NoFilterPolicy.cpp
./Log/Private/Policies/NoFormatPolicy.cpp
./Log/Private/Policies/OutStreamWritePolicy.cpp
./Log/Private/Policies/SeverityFilterPolicy.cpp
./Misc/Literals.cpp
./Misc/Literals.h
./Misc/moeAbort.h
./Misc/moeCountof.h
./Misc/moeCRTP.h
./Misc/moeEnum.h
./Misc/moeError.h
./Misc/moeFalse.h
./Misc/moeFile.h
./Misc/moeNamedType.h
./Misc/moeTypeList.h
./Misc/Private/moeAbort.cpp
./Misc/Private/moeFile.cpp
./Misc/Types.h
./Patterns/moeSingleton.h
./Preprocessor/moeAssert.h
./Preprocessor/moeBuilder.h
./Preprocessor/moeDebug.h
./Preprocessor/moeDiscard.h
./Preprocessor/moeJoin.h
./Preprocessor/moeLikely.h
./Preprocessor/moeStringize.h
./Preprocessor/moeUnusedParameter.h
./Preprocessor/Private/moeAssert.cpp
./Resource/BaseResource.h
./Resource/FileResource.cpp
./Resource/FileResource.h
./Resource/Material/BlendState/BlendEquation.h
./Resource/Material/BlendState/BlendFactor.h
./Resource/Material/BlendState/BlendStateDescriptor.cpp
./Resource/Material/BlendState/BlendStateDescriptor.h
./Resource/Material/DepthStencilState/DepthStencilComparisonFunc.h
./Resource/Material/DepthStencilState/DepthStencilStateDescriptor.cpp
./Resource/Material/DepthStencilState/DepthStencilStateDescriptor.h
./Resource/Material/DepthStencilState/StencilOps.h
./Resource/Material/DepthStencilState/StencilOpsDescriptor.h
./Resource/Material/MaterialResource.cpp
./Resource/Material/MaterialResource.h
./Resource/Material/RasterizerState/RasterizerStateDescriptor.h
./Resource/Material/ResourceSet/BindingType.h
./Resource/Material/ResourceSet/ResourceLayoutBindingDescription.h
./Resource/Material/ResourceSet/ResourceLayoutDescription.h
./Resource/Material/Shader/Module/ShaderModuleDescriptor.h
./Resource/Material/Shader/Program/ShaderProgramDescription.h
./Resource/Material/Shader/ShaderStage/ShaderStage.cpp
./Resource/Material/Shader/ShaderStage/ShaderStage.h
./Resource/Material/Shader/UniformDataKind.h
./Resource/Material/Topology/PrimitiveTopology.h
./Resource/Material/VertexLayout/VertexElementDescriptor.h
./Resource/Material/VertexLayout/VertexElementFormat.h
./Resource/Material/VertexLayout/VertexLayout.h
./Resource/Material/VertexLayout/VertexLayoutDescriptor.h
./Resource/MeshResource.cpp
./Resource/MeshResource.h
./Resource/Resource.h
./Resource/ResourceFactory.h
./Resource/ResourceManager.cpp
./Resource/ResourceManager.h
./Resource/ResourceManagerInterface.h
./Resource/ResourceRef.cpp
./Resource/ResourceRef.h
./Resource/TextureResource.cpp
./Resource/TextureResource.h
./StringFormat/moeStringFormat.h
./StringFormat/Private/moeStringFormat.internal.hpp
./Threading/Render/GLFW/GlfwRenderThread.cpp
./Threading/Render/GLFW/GlfwRenderThread.h
./Threading/Render/RenderThread.h
./Threading/ThreadPool/ThreadPool.cpp
./Threading/ThreadPool/ThreadPool.h
./Threading/ThreadPool/ThreadPool.inl
	)
	
if(WIN32)
	set(Monocle_Core_SOURCES
	
	${Monocle_Core_SOURCES} 
	
	./Debugger/Private/Windows/moeDebugger.cpp
./Log/Policies/Windows/Win_IdeWritePolicy.h
./Log/Private/Policies/Windows/Win_IdeWritePolicy.cpp
./Misc/Private/Windows/GetLastErrorAsString.cpp
./Misc/Windows/GetLastErrorAsString.h
./StringFormat/Private/Windows/Win_moeSwprintf.internal.hpp
	)
	
elseif(APPLE)
	set(Monocle_Core_SOURCES
	
	${Monocle_Core_SOURCES} 
	
	
	)
	
elseif(UNIX)
	set(Monocle_Core_SOURCES
	
	${Monocle_Core_SOURCES} 
	
	./Debugger/Private/Linux/moeDebugger.cpp
./Log/Policies/Linux/Linux_IdeWritePolicy.h
./Log/Private/Policies/Linux/Linux_IdeWritePolicy.cpp
./StringFormat/Private/Linux/Linux_moeSwprintf.internal.hpp
	)
	
	
endif()
